// lib/regions.js — central region/i18n config (browser global, loaded via <script src>).
// 5 markets: CH | AT | DE | ES | GB. Swiss branding stays; output adapts to country.
(function () {
  var REGIONS = {
    CH: { code: 'CH', flag: '🇨🇭', name: 'Schweiz',        locale: 'de-CH', currency: 'CHF', currencySymbol: 'CHF', currencyPosition: 'before-space', language: 'de', plzLabel: 'PLZ',            plzRegex: /^\d{4}$/,                               phonePrefix: '+41' },
    AT: { code: 'AT', flag: '🇦🇹', name: 'Österreich',     locale: 'de-AT', currency: 'EUR', currencySymbol: '€',   currencyPosition: 'before-space', language: 'de', plzLabel: 'PLZ',            plzRegex: /^\d{4}$/,                               phonePrefix: '+43' },
    DE: { code: 'DE', flag: '🇩🇪', name: 'Deutschland',    locale: 'de-DE', currency: 'EUR', currencySymbol: '€',   currencyPosition: 'before-space', language: 'de', plzLabel: 'PLZ',            plzRegex: /^\d{5}$/,                               phonePrefix: '+49' },
    ES: { code: 'ES', flag: '🇪🇸', name: 'España',         locale: 'es-ES', currency: 'EUR', currencySymbol: '€',   currencyPosition: 'after-space',  language: 'es', plzLabel: 'Código Postal',  plzRegex: /^\d{5}$/,                               phonePrefix: '+34' },
    GB: { code: 'GB', flag: '🇬🇧', name: 'United Kingdom', locale: 'en-GB', currency: 'GBP', currencySymbol: '£',   currencyPosition: 'before',       language: 'en', plzLabel: 'Postcode',       plzRegex: /^[A-Z]{1,2}\d[A-Z\d]? ?\d[A-Z]{2}$/i,   phonePrefix: '+44' },
  };
  var ORDER = ['CH', 'AT', 'DE', 'ES', 'GB'];

  // Same number everywhere; only symbol + position change.
  function formatPrice(amount, region) {
    var r = (typeof region === 'string' ? REGIONS[region] : region) || REGIONS.CH;
    var n = String(amount);
    if (r.currencyPosition === 'after-space') return n + ' ' + r.currencySymbol; // 49 €
    if (r.currencyPosition === 'before') return r.currencySymbol + n;            // £49
    return r.currencySymbol + ' ' + n;                                           // CHF 49 / € 49
  }

  // First-visit default = CH (Schweiz / Deutsch). KEIN Auto-Detect mehr:
  // navigator.language / Geo / VPN dürfen die Sprache NICHT erzwingen (siehe Sprach-Bug-Fix).
  // Region/Sprache wechselt der Nutzer ausschliesslich manuell (Flaggen bzw. Sprachumschalter);
  // die gespeicherte Wahl gewinnt und wird vom Aufrufer behandelt.
  function detectRegion() {
    return 'CH';
  }

  // ── i18n (DE/ES/EN) — key B2C strings. Internal GS/admin stay German. ──
  var STR = {
    de: {
      hero_title: 'Dein smarter', hero_sub2: 'Allround-Finder',
      hero_p: 'Foto machen oder Problem beschreiben – BOB findet dir den richtigen Fachmann in deiner Nähe mit dem besten Preis-Leistungs-Verhältnis.',
      scan_btn: 'Problem scannen', mic_btn: 'Mit BOB sprechen', premium_btn: 'BOB Premium & Reports',
      sound_on: '🔊 Ton aktivieren', greeting: 'Hey, mein Name ist Bob! Ich helfe dir bei jedem Problem – egal ob Handwerk oder Beauty. Wie kann ich dir helfen?',
      intro: 'Guten Tag. Ich bin BOB, Ihr digitaler Fachassistent.',
      premium_title: 'BOB Premium', reports_grp: 'Detail-Reports (einmalig)', abos_grp: 'Abos',
      free: 'Free', pro: 'Pro', mute: 'Vorlesen stummschalten', unmute: 'Vorlesen aktivieren',
      region_label: 'Region wählen', pay_secure: 'Sichere Zahlung via Stripe · Testmodus',
      disclaimer: 'Demo-Version zum Testen. Wähle dein Land 🇨🇭🇦🇹🇩🇪🇪🇸🇬🇧 oben – Sprache, Währung und Region passen sich an. Die finale App erscheint nächstes Jahr.',
      disclaimer_ok: 'Verstanden',
      // Landing
      gs_badge:'HKLS-Profi-Team', gs_title:'Profi-Team auf Abruf',
      gs_sub:'Heizung, Sanitär, Lüftung & Klima – buchen Sie ein voll ausgestattetes HKLS-Profi-Team mit fairen Stundensätzen und 24h-Antwort.',
      gs_cta:'HKLS-Dienstleistung buchen →',
      bob_badge:'KI-Scanner', bob_title:'Problem scannen & Fachmann finden',
      bob_sub:'Foto machen oder Problem beschreiben – die KI erkennt sofort, welcher Handwerker oder Dienstleister zu dir passt.',
      bob_cta:'Jetzt scannen →', landing_or:'oder',
      landing_foot:'George Solutions · Schweizer HKLS-Dienstleistung & KI-Fachmann-Finder',
      // Home
      cat_handwerk:'Handwerk', cat_handwerk_sub:'Sanitär · Elektro · Garten · Reinigung · uvm.',
      cat_beauty:'Beauty', cat_beauty_sub:'Friseur · Nägel · Massage · Barber · uvm.',
      nav_home:'Home', nav_scan:'Scannen', nav_about:'Über BOB',
      // Scan
      scan_title:'Problem scannen', scan_voice:'Sprachmemo aufnehmen',
      scan_ph:"Oder Problem tippen... z.B. 'Wasserhahn tropft' oder 'Haare schneiden'",
      ask_btn:'BOB fragen',
      // Result
      res_title:'BOBs Diagnose', res_lbl:'Diagnose abgeschlossen',
      meta_kat:'Kategorie', meta_dring:'Dringlichkeit', meta_kost:'Kosten ca.', meta_zeit:'Zeitraum',
      tips_title:'BOBs Tipps', act_title:'Was möchtest du als nächstes?',
      act_find_a:'Handwerker finden', act_find_a_sub:'BOB sucht den richtigen Fachmann für dich',
      act_find_b:'Fachmann / Anbieter finden', act_find_b_sub:'BOB findet den passenden Anbieter in deiner Nähe',
      price_free:'Gratis', price_on_order:'bei Auftragserteilung', price_once:'einmalig',
      act_angebot:'Professionelles Angebot', act_angebot_sub:'Verbindliches Angebot vom Fachmann in 24h',
      act_finder:'Anbieter in deiner Nähe finden', act_finder_sub:'Wir schicken dir die nächsten passenden Anbieter (z.B. Barbershops, Nagelstudios) per E-Mail.',
      act_pro:'BOBs Profi-Rat', act_pro_sub:'Detaillierte Experteneinschätzung', act_pro_basic:'basic',
      new_scan:'🔄 Neuen Scan starten', chat_title:'💬 Noch Fragen? Frag BOB!', chat_ph:'Frag BOB etwas…',
      fb_q:'War diese Antwort hilfreich?', fb_yes:'Ja', fb_no:'Nein', fb_correct:'Korrigieren',
      maps_title:'Fachmann in deiner Nähe', maps_sub:'Google Maps Integration kommt bald',
      richt_prefix:'💡 In deiner Region', richt_mid:'kostet das üblicherweise', richt_var:'je nach Anbieter unterschiedlich',
      // GS-Flow (Tarif + Team)
      gs_tarif_pilot_name:'Pilot', gs_tarif_pilot_desc:'Kennenlernen · 14 Tage / 3 Wochen · danach Monatsvertrag',
      gs_tarif_monat_name:'Monatsvertrag', gs_tarif_monat_desc:'Laufende Betreuung · faire Fixkonditionen',
      gs_tarif_hint:'Stundensatz inkl. Spesen. Einzel oder 2er-Team wählen Sie im nächsten Schritt.',
      gs_team_recommended:'Empfohlen', gs_team_team_tit:'👥 2er-Team', gs_team_team_sub:'Zwei eingespielte Profis vor Ort',
      gs_team_single_tit:'👤 Einzel-Techniker', gs_team_single_sub:'Ein Profi vor Ort',
      gs_tech_loading:'Techniker werden geladen…', gs_tech_skip:'Optional – Sie können einen Wunsch-Techniker wählen oder dies dem Team überlassen.',
      gs_ki_badge:'⭐ KI-Empfehlung', gs_ki_empfiehlt:'KI empfiehlt',
    },
    es: {
      hero_title: 'Tu buscador', hero_sub2: 'todoterreno',
      hero_p: 'Haz una foto o describe tu problema – BOB te encuentra al profesional adecuado cerca de ti con la mejor relación calidad-precio.',
      scan_btn: 'Escanear problema', mic_btn: 'Hablar con BOB', premium_btn: 'BOB Premium e Informes',
      sound_on: '🔊 Activar sonido', greeting: '¡Hola, me llamo Bob! Te ayudo con cualquier problema, ya sea de oficios o belleza. ¿En qué puedo ayudarte?',
      intro: 'Buenos días. Soy BOB, su asistente técnico digital.',
      premium_title: 'BOB Premium', reports_grp: 'Informes detallados (único pago)', abos_grp: 'Suscripciones',
      free: 'Free', pro: 'Pro', mute: 'Silenciar lectura', unmute: 'Activar lectura',
      region_label: 'Elegir región', pay_secure: 'Pago seguro con Stripe · Modo de prueba',
      disclaimer: 'Versión de demostración para pruebas. Elige tu país 🇨🇭🇦🇹🇩🇪🇪🇸🇬🇧 arriba – el idioma, la moneda y la región se adaptan. La app final llegará el próximo año.',
      disclaimer_ok: 'Entendido',
      // Landing
      gs_badge:'Equipo HKLS Pro', gs_title:'Equipo profesional a demanda',
      gs_sub:'Calefacción, fontanería, ventilación y climatización – reserve un equipo profesional HKLS totalmente equipado, con tarifas justas y respuesta en 24h.',
      gs_cta:'Reservar servicio HKLS →',
      bob_badge:'Escáner IA', bob_title:'Escanea tu problema y encuentra al profesional',
      bob_sub:'Haz una foto o describe tu problema – la IA reconoce al instante qué profesional o proveedor te conviene.',
      bob_cta:'Escanear ahora →', landing_or:'o',
      landing_foot:'George Solutions · Servicio HKLS suizo y buscador de profesionales con IA',
      // Home
      cat_handwerk:'Oficios', cat_handwerk_sub:'Fontanería · Electricidad · Jardín · Limpieza · y más',
      cat_beauty:'Belleza', cat_beauty_sub:'Peluquería · Uñas · Masaje · Barbería · y más',
      nav_home:'Inicio', nav_scan:'Escanear', nav_about:'Sobre BOB',
      // Scan
      scan_title:'Escanear problema', scan_voice:'Grabar nota de voz',
      scan_ph:"O escribe tu problema... p. ej. 'gotea el grifo' o 'cortar el pelo'",
      ask_btn:'Preguntar a BOB',
      // Result
      res_title:'Diagnóstico de BOB', res_lbl:'Diagnóstico completado',
      meta_kat:'Categoría', meta_dring:'Urgencia', meta_kost:'Coste aprox.', meta_zeit:'Plazo',
      tips_title:'Consejos de BOB', act_title:'¿Qué quieres hacer ahora?',
      act_find_a:'Encontrar profesional', act_find_a_sub:'BOB busca al profesional adecuado para ti',
      act_find_b:'Encontrar proveedor', act_find_b_sub:'BOB encuentra el proveedor adecuado cerca de ti',
      price_free:'Gratis', price_on_order:'al contratar', price_once:'pago único',
      act_angebot:'Presupuesto profesional', act_angebot_sub:'Presupuesto vinculante del profesional en 24h',
      act_finder:'Encontrar proveedores cerca de ti', act_finder_sub:'Te enviamos por correo los proveedores adecuados más cercanos (p. ej. barberías, salones de uñas).',
      act_pro:'Consejo Pro de BOB', act_pro_sub:'Evaluación experta detallada', act_pro_basic:'básico',
      new_scan:'🔄 Nuevo escaneo', chat_title:'💬 ¿Más preguntas? ¡Pregunta a BOB!', chat_ph:'Pregunta algo a BOB…',
      fb_q:'¿Te ha sido útil esta respuesta?', fb_yes:'Sí', fb_no:'No', fb_correct:'Corregir',
      maps_title:'Profesional cerca de ti', maps_sub:'Integración con Google Maps muy pronto',
      richt_prefix:'💡 En tu región', richt_mid:'esto suele costar', richt_var:'varía según el proveedor',
      // GS-Flow (Tarifa + Equipo)
      gs_tarif_pilot_name:'Piloto', gs_tarif_pilot_desc:'Para empezar · 14 días / 3 semanas · luego contrato mensual',
      gs_tarif_monat_name:'Contrato mensual', gs_tarif_monat_desc:'Atención continua · condiciones fijas justas',
      gs_tarif_hint:'Tarifa por hora con gastos incluidos. Elija individual o equipo de 2 en el siguiente paso.',
      gs_team_recommended:'Recomendado', gs_team_team_tit:'👥 Equipo de 2', gs_team_team_sub:'Dos profesionales compenetrados in situ',
      gs_team_single_tit:'👤 Técnico individual', gs_team_single_sub:'Un profesional in situ',
      gs_tech_loading:'Cargando técnicos…', gs_tech_skip:'Opcional: elija un técnico preferido o déjelo en manos del equipo.',
      gs_ki_badge:'⭐ Recomendación IA', gs_ki_empfiehlt:'La IA recomienda',
    },
    en: {
      hero_title: 'Your smart', hero_sub2: 'all-round finder',
      hero_p: 'Take a photo or describe your problem – BOB finds you the right professional nearby with the best value for money.',
      scan_btn: 'Scan problem', mic_btn: 'Talk to BOB', premium_btn: 'BOB Premium & Reports',
      sound_on: '🔊 Enable sound', greeting: "Hey, my name is Bob! I help you with any problem – trades or beauty. How can I help you?",
      intro: 'Good day. I am BOB, your digital expert assistant.',
      premium_title: 'BOB Premium', reports_grp: 'Detailed reports (one-time)', abos_grp: 'Subscriptions',
      free: 'Free', pro: 'Pro', mute: 'Mute read-aloud', unmute: 'Enable read-aloud',
      region_label: 'Choose region', pay_secure: 'Secure payment via Stripe · Test mode',
      disclaimer: 'Demo version for testing. Choose your country 🇨🇭🇦🇹🇩🇪🇪🇸🇬🇧 above – language, currency and region adapt. The final app launches next year.',
      disclaimer_ok: 'Got it',
      // Landing
      gs_badge:'HKLS Pro Team', gs_title:'Pro team on demand',
      gs_sub:'Heating, plumbing, ventilation & air conditioning – book a fully equipped HKLS pro team with fair hourly rates and a 24h response.',
      gs_cta:'Book HKLS service →',
      bob_badge:'AI Scanner', bob_title:'Scan your problem & find a professional',
      bob_sub:'Take a photo or describe your problem – the AI instantly recognises which tradesperson or provider fits you.',
      bob_cta:'Scan now →', landing_or:'or',
      landing_foot:'George Solutions · Swiss HKLS service & AI professional finder',
      // Home
      cat_handwerk:'Trades', cat_handwerk_sub:'Plumbing · Electrical · Garden · Cleaning · & more',
      cat_beauty:'Beauty', cat_beauty_sub:'Hairdresser · Nails · Massage · Barber · & more',
      nav_home:'Home', nav_scan:'Scan', nav_about:'About BOB',
      // Scan
      scan_title:'Scan problem', scan_voice:'Record voice memo',
      scan_ph:"Or type your problem... e.g. 'tap is dripping' or 'haircut'",
      ask_btn:'Ask BOB',
      // Result
      res_title:"BOB's diagnosis", res_lbl:'Diagnosis complete',
      meta_kat:'Category', meta_dring:'Urgency', meta_kost:'Cost approx.', meta_zeit:'Timeframe',
      tips_title:"BOB's tips", act_title:'What would you like to do next?',
      act_find_a:'Find a tradesperson', act_find_a_sub:'BOB finds the right professional for you',
      act_find_b:'Find a provider', act_find_b_sub:'BOB finds the right provider near you',
      price_free:'Free', price_on_order:'on booking', price_once:'one-time',
      act_angebot:'Professional quote', act_angebot_sub:'Binding quote from the professional within 24h',
      act_finder:'Find providers near you', act_finder_sub:'We email you the nearest matching providers (e.g. barbershops, nail salons).',
      act_pro:"BOB's Pro advice", act_pro_sub:'Detailed expert assessment', act_pro_basic:'basic',
      new_scan:'🔄 Start a new scan', chat_title:'💬 More questions? Ask BOB!', chat_ph:'Ask BOB something…',
      fb_q:'Was this answer helpful?', fb_yes:'Yes', fb_no:'No', fb_correct:'Correct',
      maps_title:'Professional near you', maps_sub:'Google Maps integration coming soon',
      richt_prefix:'💡 In your region', richt_mid:'this usually costs', richt_var:'varies by provider',
      // GS flow (tariff + team)
      gs_tarif_pilot_name:'Pilot', gs_tarif_pilot_desc:'Get started · 14 days / 3 weeks · then monthly contract',
      gs_tarif_monat_name:'Monthly contract', gs_tarif_monat_desc:'Ongoing support · fair fixed rates',
      gs_tarif_hint:'Hourly rate incl. expenses. Choose single or 2-person team in the next step.',
      gs_team_recommended:'Recommended', gs_team_team_tit:'👥 2-person team', gs_team_team_sub:'Two well-rehearsed pros on site',
      gs_team_single_tit:'👤 Single technician', gs_team_single_sub:'One pro on site',
      gs_tech_loading:'Loading technicians…', gs_tech_skip:'Optional – pick a preferred technician or leave it to the team.',
      gs_ki_badge:'⭐ AI recommendation', gs_ki_empfiehlt:'AI recommends',
    },
    fr: {
      hero_title: 'Ton chercheur', hero_sub2: 'tout-en-un',
      hero_p: 'Prends une photo ou décris ton problème – BOB te trouve le bon professionnel près de chez toi au meilleur rapport qualité-prix.',
      scan_btn: 'Scanner le problème', mic_btn: 'Parler à BOB', premium_btn: 'BOB Premium & Rapports',
      sound_on: '🔊 Activer le son', greeting: "Salut, je m'appelle Bob ! Je t'aide pour tout problème – artisanat ou beauté. Comment puis-je t'aider ?",
      intro: 'Bonjour. Je suis BOB, votre assistant technique numérique.',
      premium_title: 'BOB Premium', reports_grp: 'Rapports détaillés (paiement unique)', abos_grp: 'Abonnements',
      free: 'Free', pro: 'Pro', mute: 'Couper la lecture', unmute: 'Activer la lecture',
      region_label: 'Choisir la région', pay_secure: 'Paiement sécurisé via Stripe · Mode test',
      disclaimer: "Version de démonstration pour tests. Choisis ton pays 🇨🇭🇦🇹🇩🇪🇪🇸🇬🇧 en haut – la langue, la monnaie et la région s'adaptent. L'app finale arrive l'année prochaine.",
      disclaimer_ok: 'Compris',
      gs_badge:'Équipe pro HKLS', gs_title:'Équipe pro à la demande',
      gs_sub:'Chauffage, sanitaire, ventilation & climatisation – réservez une équipe pro HKLS entièrement équipée, à tarifs équitables et réponse sous 24h.',
      gs_cta:'Réserver un service HKLS →',
      bob_badge:'Scanner IA', bob_title:'Scanne ton problème & trouve un pro',
      bob_sub:"Prends une photo ou décris ton problème – l'IA reconnaît aussitôt quel artisan ou prestataire te convient.",
      bob_cta:'Scanner maintenant →', landing_or:'ou',
      landing_foot:'George Solutions · Service HKLS suisse & recherche de pros par IA',
      cat_handwerk:'Artisanat', cat_handwerk_sub:'Sanitaire · Électricité · Jardin · Nettoyage · etc.',
      cat_beauty:'Beauté', cat_beauty_sub:'Coiffeur · Ongles · Massage · Barbier · etc.',
      nav_home:'Accueil', nav_scan:'Scanner', nav_about:'À propos',
      scan_title:'Scanner le problème', scan_voice:'Enregistrer un mémo vocal',
      scan_ph:"Ou écris ton problème... p. ex. 'robinet qui goutte' ou 'coupe de cheveux'",
      ask_btn:'Demander à BOB',
      res_title:'Diagnostic de BOB', res_lbl:'Diagnostic terminé',
      meta_kat:'Catégorie', meta_dring:'Urgence', meta_kost:'Coût env.', meta_zeit:'Délai',
      tips_title:'Conseils de BOB', act_title:'Que veux-tu faire ensuite ?',
      act_find_a:'Trouver un artisan', act_find_a_sub:'BOB cherche le bon professionnel pour toi',
      act_find_b:'Trouver un prestataire', act_find_b_sub:'BOB trouve le bon prestataire près de chez toi',
      price_free:'Gratuit', price_on_order:'à la commande', price_once:'paiement unique',
      act_angebot:'Devis professionnel', act_angebot_sub:'Devis ferme du professionnel sous 24h',
      act_finder:'Trouver des prestataires près de chez toi', act_finder_sub:"Nous t'envoyons par e-mail les prestataires les plus proches (p. ex. barbiers, onglerie).",
      act_pro:'Conseil Pro de BOB', act_pro_sub:'Évaluation experte détaillée', act_pro_basic:'basic',
      new_scan:'🔄 Nouveau scan', chat_title:"💬 D'autres questions ? Demande à BOB !", chat_ph:'Pose une question à BOB…',
      fb_q:"Cette réponse t'a-t-elle été utile ?", fb_yes:'Oui', fb_no:'Non', fb_correct:'Corriger',
      maps_title:'Professionnel près de chez toi', maps_sub:'Intégration Google Maps bientôt disponible',
      richt_prefix:'💡 Dans ta région', richt_mid:'cela coûte généralement', richt_var:'variable selon le prestataire',
      gs_tarif_pilot_name:'Pilote', gs_tarif_pilot_desc:'Pour démarrer · 14 jours / 3 semaines · puis contrat mensuel',
      gs_tarif_monat_name:'Contrat mensuel', gs_tarif_monat_desc:'Suivi continu · conditions fixes équitables',
      gs_tarif_hint:"Tarif horaire frais compris. Choisissez individuel ou équipe de 2 à l'étape suivante.",
      gs_team_recommended:'Recommandé', gs_team_team_tit:'👥 Équipe de 2', gs_team_team_sub:'Deux pros rodés sur place',
      gs_team_single_tit:'👤 Technicien seul', gs_team_single_sub:'Un pro sur place',
      gs_tech_loading:'Chargement des techniciens…', gs_tech_skip:"Optionnel – choisissez un technicien préféré ou laissez l'équipe décider.",
      gs_ki_badge:'⭐ Recommandation IA', gs_ki_empfiehlt:"L'IA recommande",
    },
    it: {
      hero_title: 'Il tuo cercatore', hero_sub2: 'tuttofare',
      hero_p: 'Scatta una foto o descrivi il problema – BOB ti trova il professionista giusto vicino a te con il miglior rapporto qualità-prezzo.',
      scan_btn: 'Scansiona il problema', mic_btn: 'Parla con BOB', premium_btn: 'BOB Premium e Report',
      sound_on: "🔊 Attiva l'audio", greeting: 'Ciao, mi chiamo Bob! Ti aiuto con qualsiasi problema – artigianato o bellezza. Come posso aiutarti?',
      intro: 'Buongiorno. Sono BOB, il suo assistente tecnico digitale.',
      premium_title: 'BOB Premium', reports_grp: 'Report dettagliati (pagamento unico)', abos_grp: 'Abbonamenti',
      free: 'Free', pro: 'Pro', mute: 'Disattiva lettura', unmute: 'Attiva lettura',
      region_label: 'Scegli la regione', pay_secure: 'Pagamento sicuro con Stripe · Modalità test',
      disclaimer: "Versione demo per test. Scegli il tuo paese 🇨🇭🇦🇹🇩🇪🇪🇸🇬🇧 in alto – lingua, valuta e regione si adattano. L'app finale arriverà l'anno prossimo.",
      disclaimer_ok: 'Capito',
      gs_badge:'Team pro HKLS', gs_title:'Team pro su richiesta',
      gs_sub:'Riscaldamento, sanitari, ventilazione e climatizzazione – prenota un team pro HKLS completamente attrezzato, con tariffe eque e risposta in 24h.',
      gs_cta:'Prenota un servizio HKLS →',
      bob_badge:'Scanner IA', bob_title:'Scansiona il problema e trova un pro',
      bob_sub:"Scatta una foto o descrivi il problema – l'IA riconosce subito quale artigiano o fornitore fa per te.",
      bob_cta:'Scansiona ora →', landing_or:'oppure',
      landing_foot:'George Solutions · Servizio HKLS svizzero e ricerca di professionisti con IA',
      cat_handwerk:'Artigianato', cat_handwerk_sub:'Sanitari · Elettricità · Giardino · Pulizie · ecc.',
      cat_beauty:'Bellezza', cat_beauty_sub:'Parrucchiere · Unghie · Massaggi · Barbiere · ecc.',
      nav_home:'Home', nav_scan:'Scansiona', nav_about:'Su BOB',
      scan_title:'Scansiona il problema', scan_voice:'Registra un memo vocale',
      scan_ph:"Oppure scrivi il problema... es. 'rubinetto che gocciola' o 'taglio di capelli'",
      ask_btn:'Chiedi a BOB',
      res_title:'Diagnosi di BOB', res_lbl:'Diagnosi completata',
      meta_kat:'Categoria', meta_dring:'Urgenza', meta_kost:'Costo circa', meta_zeit:'Tempistica',
      tips_title:'Consigli di BOB', act_title:'Cosa vuoi fare adesso?',
      act_find_a:'Trova un artigiano', act_find_a_sub:'BOB cerca il professionista giusto per te',
      act_find_b:'Trova un fornitore', act_find_b_sub:'BOB trova il fornitore giusto vicino a te',
      price_free:'Gratis', price_on_order:"all'ordine", price_once:'pagamento unico',
      act_angebot:'Preventivo professionale', act_angebot_sub:'Preventivo vincolante dal professionista in 24h',
      act_finder:'Trova fornitori vicino a te', act_finder_sub:'Ti inviamo via e-mail i fornitori più vicini adatti (es. barbieri, centri estetici).',
      act_pro:'Consiglio Pro di BOB', act_pro_sub:'Valutazione esperta dettagliata', act_pro_basic:'basic',
      new_scan:'🔄 Nuova scansione', chat_title:'💬 Altre domande? Chiedi a BOB!', chat_ph:'Chiedi qualcosa a BOB…',
      fb_q:'Questa risposta ti è stata utile?', fb_yes:'Sì', fb_no:'No', fb_correct:'Correggi',
      maps_title:'Professionista vicino a te', maps_sub:'Integrazione Google Maps in arrivo',
      richt_prefix:'💡 Nella tua regione', richt_mid:'di solito costa', richt_var:'variabile secondo il fornitore',
      gs_tarif_pilot_name:'Pilota', gs_tarif_pilot_desc:'Per iniziare · 14 giorni / 3 settimane · poi contratto mensile',
      gs_tarif_monat_name:'Contratto mensile', gs_tarif_monat_desc:'Assistenza continua · condizioni fisse eque',
      gs_tarif_hint:'Tariffa oraria spese incluse. Scegli singolo o team di 2 nel passaggio successivo.',
      gs_team_recommended:'Consigliato', gs_team_team_tit:'👥 Team di 2', gs_team_team_sub:'Due professionisti affiatati sul posto',
      gs_team_single_tit:'👤 Tecnico singolo', gs_team_single_sub:'Un professionista sul posto',
      gs_tech_loading:'Caricamento tecnici…', gs_tech_skip:'Opzionale – scegli un tecnico preferito o lascia decidere al team.',
      gs_ki_badge:'⭐ Raccomandazione IA', gs_ki_empfiehlt:"L'IA consiglia",
    },
  };
  function t(key, lang) { var L = STR[lang] || STR.de; return (key in L) ? L[key] : (STR.de[key] || key); }

  window.BB_REGIONS = REGIONS;
  window.BB_REGION_ORDER = ORDER;
  window.bbFormatPrice = formatPrice;
  window.bbDetectRegion = detectRegion;
  window.bbT = t;
})();
