// lib/regions.js — central region/i18n config (browser global, loaded via <script src>).
// 5 markets: CH | AT | DE | ES | GB. Swiss branding stays; output adapts to country.
(function () {
  var REGIONS = {
    CH: { code: 'CH', flag: '🇨🇭', name: 'Schweiz',        locale: 'de-CH', currency: 'CHF', currencySymbol: 'CHF', currencyPosition: 'before-space', language: 'de', plzLabel: 'PLZ',            plzRegex: /^\d{4}$/,                               phonePrefix: '+41' },
    AT: { code: 'AT', flag: '🇦🇹', name: 'Österreich',     locale: 'de-AT', currency: 'EUR', currencySymbol: '€',   currencyPosition: 'before-space', language: 'de', plzLabel: 'PLZ',            plzRegex: /^\d{4}$/,                               phonePrefix: '+43' },
    DE: { code: 'DE', flag: '🇩🇪', name: 'Deutschland',    locale: 'de-DE', currency: 'EUR', currencySymbol: '€',   currencyPosition: 'before-space', language: 'de', plzLabel: 'PLZ',            plzRegex: /^\d{5}$/,                               phonePrefix: '+49' },
    ES: { code: 'ES', flag: '🇪🇸', name: 'España',         locale: 'es-ES', currency: 'EUR', currencySymbol: '€',   currencyPosition: 'after-space',  language: 'es', plzLabel: 'Código Postal',  plzRegex: /^\d{5}$/,                               phonePrefix: '+34' },
    GB: { code: 'GB', flag: '🇬🇧', name: 'United Kingdom', locale: 'en-GB', currency: 'GBP', currencySymbol: '£',   currencyPosition: 'before',       language: 'en', plzLabel: 'Postcode',       plzRegex: /^[A-Z]{1,2}\d[A-Z\d]? ?\d[A-Z]{2}$/i,   phonePrefix: '+44' },
  };
  var ORDER = ['CH', 'AT', 'DE', 'ES', 'GB'];

  // Same number everywhere; only symbol + position change.
  function formatPrice(amount, region) {
    var r = (typeof region === 'string' ? REGIONS[region] : region) || REGIONS.CH;
    var n = String(amount);
    if (r.currencyPosition === 'after-space') return n + ' ' + r.currencySymbol; // 49 €
    if (r.currencyPosition === 'before') return r.currencySymbol + n;            // £49
    return r.currencySymbol + ' ' + n;                                           // CHF 49 / € 49
  }

  // First-visit default = CH (Schweiz / Deutsch). KEIN Auto-Detect mehr:
  // navigator.language / Geo / VPN dürfen die Sprache NICHT erzwingen (siehe Sprach-Bug-Fix).
  // Region/Sprache wechselt der Nutzer ausschliesslich manuell (Flaggen bzw. Sprachumschalter);
  // die gespeicherte Wahl gewinnt und wird vom Aufrufer behandelt.
  function detectRegion() {
    return 'CH';
  }

  // ── i18n (DE/ES/EN) — key B2C strings. Internal GS/admin stay German. ──
  var STR = {
    de: {
      hero_title: 'Dein smarter', hero_sub2: 'Allround-Finder',
      hero_p: 'Foto machen oder Problem beschreiben – BOB findet dir den richtigen Fachmann in deiner Nähe mit dem besten Preis-Leistungs-Verhältnis.',
      scan_btn: 'Problem scannen', mic_btn: 'Mit BOB sprechen', premium_btn: 'BOB Premium & Reports',
      sound_on: '🔊 Ton aktivieren', greeting: 'Hey, mein Name ist Bob! Ich helfe dir bei jedem Problem – egal ob Handwerk oder Beauty. Wie kann ich dir helfen?',
      intro: 'Guten Tag. Ich bin BOB, Ihr digitaler Fachassistent.',
      premium_title: 'BOB Premium', reports_grp: 'Detail-Reports (einmalig)', abos_grp: 'Abos',
      free: 'Free', pro: 'Pro', mute: 'Vorlesen stummschalten', unmute: 'Vorlesen aktivieren',
      region_label: 'Region wählen', pay_secure: 'Sichere Zahlung via Stripe · Testmodus',
      disclaimer: 'Demo-Version zum Testen. Wähle dein Land 🇨🇭🇦🇹🇩🇪🇪🇸🇬🇧 oben – Sprache, Währung und Region passen sich an. Die finale App erscheint nächstes Jahr.',
      disclaimer_ok: 'Verstanden',
      // Landing
      gs_badge:'HKLS-Profi-Team', gs_title:'Profi-Team auf Abruf',
      gs_sub:'Heizung, Sanitär, Lüftung & Klima – buchen Sie ein voll ausgestattetes HKLS-Profi-Team mit fairen Stundensätzen und 24h-Antwort.',
      gs_cta:'HKLS-Dienstleistung buchen →',
      bob_badge:'KI-Scanner', bob_title:'Problem scannen & Fachmann finden',
      bob_sub:'Foto machen oder Problem beschreiben – die KI erkennt sofort, welcher Handwerker oder Dienstleister zu dir passt.',
      bob_cta:'Jetzt scannen →', landing_or:'oder',
      landing_foot:'George Solutions · Schweizer HKLS-Dienstleistung & KI-Fachmann-Finder',
      // Home
      cat_handwerk:'Handwerk', cat_handwerk_sub:'Sanitär · Elektro · Garten · Reinigung · uvm.',
      cat_beauty:'Beauty', cat_beauty_sub:'Friseur · Nägel · Massage · Barber · uvm.',
      nav_home:'Home', nav_scan:'Scannen', nav_about:'Über BOB',
      // Scan
      scan_title:'Problem scannen', scan_voice:'Sprachmemo aufnehmen',
      scan_ph:"Oder Problem tippen... z.B. 'Wasserhahn tropft' oder 'Haare schneiden'",
      ask_btn:'BOB fragen',
      // Result
      res_title:'BOBs Diagnose', res_lbl:'Diagnose abgeschlossen',
      meta_kat:'Kategorie', meta_dring:'Dringlichkeit', meta_kost:'Kosten ca.', meta_zeit:'Zeitraum',
      tips_title:'BOBs Tipps', act_title:'Was möchtest du als nächstes?',
      act_find_a:'Handwerker finden', act_find_a_sub:'BOB sucht den richtigen Fachmann für dich',
      act_find_b:'Fachmann / Anbieter finden', act_find_b_sub:'BOB findet den passenden Anbieter in deiner Nähe',
      price_free:'Gratis', price_on_order:'bei Auftragserteilung', price_once:'einmalig',
      act_angebot:'Professionelles Angebot', act_angebot_sub:'Verbindliches Angebot vom Fachmann in 24h',
      act_finder:'Anbieter in deiner Nähe finden', act_finder_sub:'Wir schicken dir die nächsten passenden Anbieter (z.B. Barbershops, Nagelstudios) per E-Mail.',
      act_pro:'BOBs Profi-Rat', act_pro_sub:'Detaillierte Experteneinschätzung', act_pro_basic:'basic',
      new_scan:'🔄 Neuen Scan starten', chat_title:'💬 Noch Fragen? Frag BOB!', chat_ph:'Frag BOB etwas…',
      fb_q:'War diese Antwort hilfreich?', fb_yes:'Ja', fb_no:'Nein', fb_correct:'Korrigieren',
      maps_title:'Fachmann in deiner Nähe', maps_sub:'Google Maps Integration kommt bald',
      richt_prefix:'💡 In deiner Region', richt_mid:'kostet das üblicherweise', richt_var:'je nach Anbieter unterschiedlich',
      // GS-Flow (Tarif + Team)
      gs_tarif_pilot_name:'Pilot', gs_tarif_pilot_desc:'Kennenlernen · 14 Tage / 3 Wochen · danach Monatsvertrag',
      gs_tarif_monat_name:'Monatsvertrag', gs_tarif_monat_desc:'Laufende Betreuung · faire Fixkonditionen',
      gs_tarif_hint:'Stundensatz inkl. Spesen. Einzel oder 2er-Team wählen Sie im nächsten Schritt.',
      gs_team_recommended:'Empfohlen', gs_team_team_tit:'👥 2er-Team', gs_team_team_sub:'Zwei eingespielte Profis vor Ort',
      gs_team_single_tit:'👤 Einzel-Techniker', gs_team_single_sub:'Ein Profi vor Ort',
      gs_tech_loading:'Techniker werden geladen…', gs_tech_skip:'Optional – Sie können einen Wunsch-Techniker wählen oder dies dem Team überlassen.',
      gs_ki_badge:'⭐ KI-Empfehlung', gs_ki_empfiehlt:'KI empfiehlt',
      // GS-Flow (Kunden-Funnel) – i18n
      gsf_home_tit:'HKLS-<span>Expertise</span><br>auf Abruf',
      gsf_home_sub:'Professionelle Gebäudetechnik-Dienstleistungen für Unternehmen, Liegenschaftsverwaltungen und Facility Manager.',
      gsf_svc_heizung:'🔥 Heizung',
      gsf_svc_sanitaer:'🚿 Sanitär',
      gsf_svc_lueftung:'💨 Lüftung',
      gsf_svc_klima:'❄️ Klima',
      gsf_home_akt_t:'Aktion: Erste 2 Stunden gratis',
      gsf_home_akt_s:'Gilt ab Monatsvertrag (nicht beim Pilot) · seriös & unverbindlich',
      gsf_home_cta:'Neues Projekt erfassen',
      gsf_24h_t:'24h Antwort-Versprechen',
      gsf_home_prom_s:'Kein Login · Mobile First · Kein Risiko',
      gsf_home_pilotnow:'Pilot-Aktion, nur jetzt',
      gsf_home_login:'🔑 Partner / Techniker Login',
      gsf_phone_t:'Lieber persönlich?',
      gsf_phone_s:'Erstgespräch: info@george-solutions.ch',
      gsf_phone_num:'✉️ Schreiben',
      gsf_nav_erfassung:'Projekterfassung',
      gsf_nav_datenblatt:'Projektdatenblatt',
      gsf_nav_tarif:'Tarif-Auswahl',
      gsf_nav_team:'Unser Team',
      gsf_nav_kontakt:'Kontakt & Verfügbarkeit',
      gsf_nav_bestaet:'Anfrage bestätigen',
      gsf_erf_akt_t:'Erste 2 Stunden gratis',
      gsf_erf_akt_s:'ab Monatsvertrag (nicht beim Pilot)',
      gsf_l_projname:'Projektname',
      gsf_ph_projname:'z.B. Heizungsrevision Objekt Zürich',
      gsf_l_bereich:'Bereich',
      gsf_chip_kombiniert:'🔧 Kombiniert',
      gsf_l_objekt:'Objekttyp',
      gsf_chip_efh:'🏠 EFH',
      gsf_chip_mfh:'🏢 MFH',
      gsf_chip_gewerbe:'🏪 Gewerbe',
      gsf_chip_industrie:'🏭 Industrie',
      gsf_l_desc:'Projektbeschreibung',
      gsf_ph_desc:'Beschreiben Sie das Projekt: Was soll gemacht werden? Welche Probleme bestehen? Grösse des Objekts...',
      gsf_l_dring:'Dringlichkeit',
      gsf_chip_normal:'📅 Normal',
      gsf_chip_dringend:'⚡ Dringend',
      gsf_chip_sehrdringend:'🚨 Sehr dringend',
      gsf_btn_analyse:'KI-Analyse starten',
      gsf_db_lbl:'KI-Analyse abgeschlossen',
      gsf_db_m_umfang:'Umfang',
      gsf_db_m_std:'Geschätzte Stunden',
      gsf_db_m_prio:'Priorität',
      gsf_db_steps:'📋 Nächste Schritte',
      gsf_db_tech:'⚙️ Technische Hinweise',
      gsf_btn_tarifwahl:'Tarif wählen →',
      gsf_weiter:'Weiter →',
      gsf_near_ph:'Ihre PLZ – Techniker in Ihrer Nähe',
      gsf_tech_hint:'👷 Verfügbare Techniker für Ihr Projekt',
      gsf_l_vorname:'Vorname *',
      gsf_l_nachname:'Nachname *',
      gsf_l_firma:'Firma',
      gsf_l_strasse:'Strasse & Hausnummer *',
      gsf_l_plz:'PLZ *',
      gsf_l_ort:'Ort *',
      gsf_l_tel:'Telefon *',
      gsf_l_email:'E-Mail *',
      gsf_l_start:'Gewünschter Start',
      gsf_l_infos:'Zusätzliche Infos',
      gsf_ph_firma:'Firmenname (optional)',
      gsf_ph_strasse:'z.B. Musterstrasse 12',
      gsf_ph_tel:'Telefon / WhatsApp',
      gsf_ph_email:'E-Mail-Adresse',
      gsf_ph_notiz:'Besonderheiten, Zugangsinformationen, weitere Wünsche...',
      gsf_chip_asap:'⚡ ASAP',
      gsf_chip_thisweek:'📅 Diese Woche',
      gsf_chip_nextweek:'🗓️ Nächste Woche',
      gsf_chip_open:'🔄 Termin offen',
      gsf_leadhint:'📌 Bitte Telefon <strong>und</strong> E-Mail angeben. Bei einem Tippfehler in der Telefonnummer kontaktieren wir Sie zusätzlich per E-Mail zur Terminvereinbarung.',
      gsf_bestaet_intro:'Bitte prüfen Sie Ihre Anfrage vor dem Absenden:',
      gsf_24h_s2:'Das GS-Team meldet sich innerhalb von 24 Stunden.',
      gsf_btn_send:'Anfrage jetzt senden',
      gsf_bestaet_privacy:'Ihre Daten werden vertraulich behandelt und nur für diese Anfrage verwendet.',
      gsf_buch_tit:'Anfrage gesendet!',
      gsf_buch_sub:'Das George Solutions Team hat Ihre Anfrage erhalten und meldet sich innerhalb von 24 Stunden mit einem konkreten Angebot.',
      gsf_tk_projekt:'Projekt',
      gsf_tk_tarif:'Gewählter Tarif',
      gsf_tk_team:'Team',
      gsf_tk_status:'Status',
      gsf_buch_status_val:'✅ Anfrage eingegangen',
      gsf_buch_erst_t:'📞 Lieber schnell persönlich klären?',
      gsf_buch_erst_s:'Kostenloses Erstgespräch – wir rufen Sie innerhalb von 2 Stunden zurück (an Werktagen).',
      gsf_buch_erst_btn:'📞 Kostenloses Erstgespräch anfordern',
      gsf_buch_erst_note:'Unverbindlich & kostenlos.',
      gsf_buch_acct_t:'📩 Status live verfolgen?',
      gsf_buch_acct_s:'Optional – erhalten Sie einen Login-Link per E-Mail, um Ihre Anfrage & Rechnungen zu sehen.',
      gsf_buch_acct_btn:'🔑 Login-Link senden',
      gsf_btn_neu:'+ Neues Projekt',
      gsf_btn_backbob:'Zurück zu Baby BOB',
      gsf_dyn_team_lbl:'2er-Team',
      gsf_dyn_single_lbl:'Einzel-Techniker',
      gsf_dyn_pp:'/h pro Person',
      gsf_dyn_total:'gesamt',
      gsf_dyn_perhour:'pro Stunde',
      gsf_dyn_perhour_total:'pro Stunde gesamt',
      gsf_dyn_oneonsite:'ein Profi vor Ort',
      gsf_dyn_choose_team:'Ihr 2er-Team wählen',
      gsf_dyn_team_note:'Feste, eingespielte 2er-Teams – beide Profis kommen voll einsatzbereit zu Ihnen.',
      gsf_dyn_single_note:'Sie wählen Ihren Wunsch-Techniker frei aus unserem Team – oder überlassen die Zuteilung der Dispo.',
      gsf_dyn_team_decides:'Team entscheidet',
      gsf_dyn_avail_now:'aktuell verfügbar',
      gsf_dyn_in_network:'Techniker im Netzwerk',
      gsf_dyn_near:'📍 In Ihrer Nähe',
      gsf_dyn_more_network:'Weitere im Netzwerk',
      gsf_dyn_no_profiles:'Aktuell sind keine Techniker-Profile hinterlegt. Das Team wird Ihrem Projekt passend zugeteilt.',
      gsf_dyn_last_upd:'Zuletzt aktualisiert',
      gsf_sum_projekt:'Projekt',
      gsf_sum_objekt:'Objekttyp',
      gsf_sum_dring:'Dringlichkeit',
      gsf_sum_std:'Geschätzte Stunden',
      gsf_sum_tarif:'Gewählter Tarif',
      gsf_sum_team:'Team',
      gsf_sum_tech:'Techniker',
      gsf_sum_wunsch:'Wunsch-Techniker',
      gsf_sum_start:'Gewünschter Start',
      gsf_sum_vorname:'Vorname',
      gsf_sum_nachname:'Nachname',
      gsf_sum_firma:'Firma',
      gsf_sum_adresse:'Adresse',
      gsf_sum_tel:'Telefon',
      gsf_sum_email:'E-Mail',
    },
    es: {
      hero_title: 'Tu buscador', hero_sub2: 'todoterreno',
      hero_p: 'Haz una foto o describe tu problema – BOB te encuentra al profesional adecuado cerca de ti con la mejor relación calidad-precio.',
      scan_btn: 'Escanear problema', mic_btn: 'Hablar con BOB', premium_btn: 'BOB Premium e Informes',
      sound_on: '🔊 Activar sonido', greeting: '¡Hola, me llamo Bob! Te ayudo con cualquier problema, ya sea de oficios o belleza. ¿En qué puedo ayudarte?',
      intro: 'Buenos días. Soy BOB, su asistente técnico digital.',
      premium_title: 'BOB Premium', reports_grp: 'Informes detallados (único pago)', abos_grp: 'Suscripciones',
      free: 'Free', pro: 'Pro', mute: 'Silenciar lectura', unmute: 'Activar lectura',
      region_label: 'Elegir región', pay_secure: 'Pago seguro con Stripe · Modo de prueba',
      disclaimer: 'Versión de demostración para pruebas. Elige tu país 🇨🇭🇦🇹🇩🇪🇪🇸🇬🇧 arriba – el idioma, la moneda y la región se adaptan. La app final llegará el próximo año.',
      disclaimer_ok: 'Entendido',
      // Landing
      gs_badge:'Equipo HKLS Pro', gs_title:'Equipo profesional a demanda',
      gs_sub:'Calefacción, fontanería, ventilación y climatización – reserve un equipo profesional HKLS totalmente equipado, con tarifas justas y respuesta en 24h.',
      gs_cta:'Reservar servicio HKLS →',
      bob_badge:'Escáner IA', bob_title:'Escanea tu problema y encuentra al profesional',
      bob_sub:'Haz una foto o describe tu problema – la IA reconoce al instante qué profesional o proveedor te conviene.',
      bob_cta:'Escanear ahora →', landing_or:'o',
      landing_foot:'George Solutions · Servicio HKLS suizo y buscador de profesionales con IA',
      // Home
      cat_handwerk:'Oficios', cat_handwerk_sub:'Fontanería · Electricidad · Jardín · Limpieza · y más',
      cat_beauty:'Belleza', cat_beauty_sub:'Peluquería · Uñas · Masaje · Barbería · y más',
      nav_home:'Inicio', nav_scan:'Escanear', nav_about:'Sobre BOB',
      // Scan
      scan_title:'Escanear problema', scan_voice:'Grabar nota de voz',
      scan_ph:"O escribe tu problema... p. ej. 'gotea el grifo' o 'cortar el pelo'",
      ask_btn:'Preguntar a BOB',
      // Result
      res_title:'Diagnóstico de BOB', res_lbl:'Diagnóstico completado',
      meta_kat:'Categoría', meta_dring:'Urgencia', meta_kost:'Coste aprox.', meta_zeit:'Plazo',
      tips_title:'Consejos de BOB', act_title:'¿Qué quieres hacer ahora?',
      act_find_a:'Encontrar profesional', act_find_a_sub:'BOB busca al profesional adecuado para ti',
      act_find_b:'Encontrar proveedor', act_find_b_sub:'BOB encuentra el proveedor adecuado cerca de ti',
      price_free:'Gratis', price_on_order:'al contratar', price_once:'pago único',
      act_angebot:'Presupuesto profesional', act_angebot_sub:'Presupuesto vinculante del profesional en 24h',
      act_finder:'Encontrar proveedores cerca de ti', act_finder_sub:'Te enviamos por correo los proveedores adecuados más cercanos (p. ej. barberías, salones de uñas).',
      act_pro:'Consejo Pro de BOB', act_pro_sub:'Evaluación experta detallada', act_pro_basic:'básico',
      new_scan:'🔄 Nuevo escaneo', chat_title:'💬 ¿Más preguntas? ¡Pregunta a BOB!', chat_ph:'Pregunta algo a BOB…',
      fb_q:'¿Te ha sido útil esta respuesta?', fb_yes:'Sí', fb_no:'No', fb_correct:'Corregir',
      maps_title:'Profesional cerca de ti', maps_sub:'Integración con Google Maps muy pronto',
      richt_prefix:'💡 En tu región', richt_mid:'esto suele costar', richt_var:'varía según el proveedor',
      // GS-Flow (Tarifa + Equipo)
      gs_tarif_pilot_name:'Piloto', gs_tarif_pilot_desc:'Para empezar · 14 días / 3 semanas · luego contrato mensual',
      gs_tarif_monat_name:'Contrato mensual', gs_tarif_monat_desc:'Atención continua · condiciones fijas justas',
      gs_tarif_hint:'Tarifa por hora con gastos incluidos. Elija individual o equipo de 2 en el siguiente paso.',
      gs_team_recommended:'Recomendado', gs_team_team_tit:'👥 Equipo de 2', gs_team_team_sub:'Dos profesionales compenetrados in situ',
      gs_team_single_tit:'👤 Técnico individual', gs_team_single_sub:'Un profesional in situ',
      gs_tech_loading:'Cargando técnicos…', gs_tech_skip:'Opcional: elija un técnico preferido o déjelo en manos del equipo.',
      gs_ki_badge:'⭐ Recomendación IA', gs_ki_empfiehlt:'La IA recomienda',
      // GS-Flow (Kunden-Funnel) – i18n
      gsf_home_tit:'Experiencia <span>HKLS</span><br>a demanda',
      gsf_home_sub:'Servicios profesionales de tecnología de edificios para empresas, administraciones de fincas y facility managers.',
      gsf_svc_heizung:'🔥 Calefacción',
      gsf_svc_sanitaer:'🚿 Fontanería',
      gsf_svc_lueftung:'💨 Ventilación',
      gsf_svc_klima:'❄️ Climatización',
      gsf_home_akt_t:'Oferta: primeras 2 horas gratis',
      gsf_home_akt_s:'Válido desde el contrato mensual (no en el Piloto) · serio y sin compromiso',
      gsf_home_cta:'Crear nuevo proyecto',
      gsf_24h_t:'Respuesta garantizada en 24h',
      gsf_home_prom_s:'Sin registro · Mobile first · Sin riesgo',
      gsf_home_pilotnow:'Oferta Piloto, solo ahora',
      gsf_home_login:'🔑 Acceso socio / técnico',
      gsf_phone_t:'¿Prefiere hablar?',
      gsf_phone_s:'Primera consulta: info@george-solutions.ch',
      gsf_phone_num:'✉️ Escribir',
      gsf_nav_erfassung:'Registro del proyecto',
      gsf_nav_datenblatt:'Ficha del proyecto',
      gsf_nav_tarif:'Elegir tarifa',
      gsf_nav_team:'Nuestro equipo',
      gsf_nav_kontakt:'Contacto y disponibilidad',
      gsf_nav_bestaet:'Confirmar solicitud',
      gsf_erf_akt_t:'Primeras 2 horas gratis',
      gsf_erf_akt_s:'desde el contrato mensual (no en el Piloto)',
      gsf_l_projname:'Nombre del proyecto',
      gsf_ph_projname:'p. ej. revisión de calefacción, obra Zúrich',
      gsf_l_bereich:'Área',
      gsf_chip_kombiniert:'🔧 Combinado',
      gsf_l_objekt:'Tipo de inmueble',
      gsf_chip_efh:'🏠 Casa',
      gsf_chip_mfh:'🏢 Edificio',
      gsf_chip_gewerbe:'🏪 Comercial',
      gsf_chip_industrie:'🏭 Industria',
      gsf_l_desc:'Descripción del proyecto',
      gsf_ph_desc:'Describa el proyecto: ¿qué hay que hacer? ¿qué problemas hay? tamaño del inmueble...',
      gsf_l_dring:'Urgencia',
      gsf_chip_normal:'📅 Normal',
      gsf_chip_dringend:'⚡ Urgente',
      gsf_chip_sehrdringend:'🚨 Muy urgente',
      gsf_btn_analyse:'Iniciar análisis IA',
      gsf_db_lbl:'Análisis IA completado',
      gsf_db_m_umfang:'Alcance',
      gsf_db_m_std:'Horas estimadas',
      gsf_db_m_prio:'Prioridad',
      gsf_db_steps:'📋 Próximos pasos',
      gsf_db_tech:'⚙️ Notas técnicas',
      gsf_btn_tarifwahl:'Elegir tarifa →',
      gsf_weiter:'Continuar →',
      gsf_near_ph:'Su código postal – técnicos cerca',
      gsf_tech_hint:'👷 Técnicos disponibles para su proyecto',
      gsf_l_vorname:'Nombre *',
      gsf_l_nachname:'Apellido *',
      gsf_l_firma:'Empresa',
      gsf_l_strasse:'Calle y número *',
      gsf_l_plz:'C. P. *',
      gsf_l_ort:'Localidad *',
      gsf_l_tel:'Teléfono *',
      gsf_l_email:'Correo *',
      gsf_l_start:'Inicio deseado',
      gsf_l_infos:'Información adicional',
      gsf_ph_firma:'Nombre de empresa (opcional)',
      gsf_ph_strasse:'p. ej. Calle Ejemplo 12',
      gsf_ph_tel:'Teléfono / WhatsApp',
      gsf_ph_email:'Dirección de correo',
      gsf_ph_notiz:'Particularidades, accesos, otros deseos...',
      gsf_chip_asap:'⚡ ASAP',
      gsf_chip_thisweek:'📅 Esta semana',
      gsf_chip_nextweek:'🗓️ Próxima semana',
      gsf_chip_open:'🔄 Fecha abierta',
      gsf_leadhint:'📌 Indique teléfono <strong>y</strong> correo. Si el número tiene un error, también le contactaremos por correo para concertar una cita.',
      gsf_bestaet_intro:'Revise su solicitud antes de enviar:',
      gsf_24h_s2:'El equipo GS le responderá en 24 horas.',
      gsf_btn_send:'Enviar solicitud',
      gsf_bestaet_privacy:'Sus datos son confidenciales y se usan solo para esta solicitud.',
      gsf_buch_tit:'¡Solicitud enviada!',
      gsf_buch_sub:'El equipo de George Solutions ha recibido su solicitud y responderá en 24 horas con una oferta concreta.',
      gsf_tk_projekt:'Proyecto',
      gsf_tk_tarif:'Tarifa elegida',
      gsf_tk_team:'Equipo',
      gsf_tk_status:'Estado',
      gsf_buch_status_val:'✅ Solicitud recibida',
      gsf_buch_erst_t:'📞 ¿Prefiere hablarlo rápido?',
      gsf_buch_erst_s:'Primera consulta gratis – le llamamos en 2 horas (días laborables).',
      gsf_buch_erst_btn:'📞 Solicitar consulta gratuita',
      gsf_buch_erst_note:'Sin compromiso y gratis.',
      gsf_buch_acct_t:'📩 ¿Seguir el estado en vivo?',
      gsf_buch_acct_s:'Opcional – reciba un enlace de acceso por correo para ver su solicitud y facturas.',
      gsf_buch_acct_btn:'🔑 Enviar enlace de acceso',
      gsf_btn_neu:'+ Nuevo proyecto',
      gsf_btn_backbob:'Volver a Baby BOB',
      gsf_dyn_team_lbl:'Equipo de 2',
      gsf_dyn_single_lbl:'Técnico individual',
      gsf_dyn_pp:'/h por persona',
      gsf_dyn_total:'en total',
      gsf_dyn_perhour:'por hora',
      gsf_dyn_perhour_total:'por hora en total',
      gsf_dyn_oneonsite:'un profesional in situ',
      gsf_dyn_choose_team:'Elija su equipo de 2',
      gsf_dyn_team_note:'Equipos de 2 fijos y compenetrados – ambos profesionales llegan listos para trabajar.',
      gsf_dyn_single_note:'Elija su técnico preferido de nuestro equipo – o deje la asignación a la central.',
      gsf_dyn_team_decides:'Decide el equipo',
      gsf_dyn_avail_now:'disponibles ahora',
      gsf_dyn_in_network:'técnicos en la red',
      gsf_dyn_near:'📍 Cerca de usted',
      gsf_dyn_more_network:'Más en la red',
      gsf_dyn_no_profiles:'Por ahora no hay perfiles de técnicos. El equipo se asignará según su proyecto.',
      gsf_dyn_last_upd:'Última actualización',
      gsf_sum_projekt:'Proyecto',
      gsf_sum_objekt:'Tipo de inmueble',
      gsf_sum_dring:'Urgencia',
      gsf_sum_std:'Horas estimadas',
      gsf_sum_tarif:'Tarifa elegida',
      gsf_sum_team:'Equipo',
      gsf_sum_tech:'Técnico',
      gsf_sum_wunsch:'Técnico preferido',
      gsf_sum_start:'Inicio deseado',
      gsf_sum_vorname:'Nombre',
      gsf_sum_nachname:'Apellido',
      gsf_sum_firma:'Empresa',
      gsf_sum_adresse:'Dirección',
      gsf_sum_tel:'Teléfono',
      gsf_sum_email:'Correo',
    },
    en: {
      hero_title: 'Your smart', hero_sub2: 'all-round finder',
      hero_p: 'Take a photo or describe your problem – BOB finds you the right professional nearby with the best value for money.',
      scan_btn: 'Scan problem', mic_btn: 'Talk to BOB', premium_btn: 'BOB Premium & Reports',
      sound_on: '🔊 Enable sound', greeting: "Hey, my name is Bob! I help you with any problem – trades or beauty. How can I help you?",
      intro: 'Good day. I am BOB, your digital expert assistant.',
      premium_title: 'BOB Premium', reports_grp: 'Detailed reports (one-time)', abos_grp: 'Subscriptions',
      free: 'Free', pro: 'Pro', mute: 'Mute read-aloud', unmute: 'Enable read-aloud',
      region_label: 'Choose region', pay_secure: 'Secure payment via Stripe · Test mode',
      disclaimer: 'Demo version for testing. Choose your country 🇨🇭🇦🇹🇩🇪🇪🇸🇬🇧 above – language, currency and region adapt. The final app launches next year.',
      disclaimer_ok: 'Got it',
      // Landing
      gs_badge:'HKLS Pro Team', gs_title:'Pro team on demand',
      gs_sub:'Heating, plumbing, ventilation & air conditioning – book a fully equipped HKLS pro team with fair hourly rates and a 24h response.',
      gs_cta:'Book HKLS service →',
      bob_badge:'AI Scanner', bob_title:'Scan your problem & find a professional',
      bob_sub:'Take a photo or describe your problem – the AI instantly recognises which tradesperson or provider fits you.',
      bob_cta:'Scan now →', landing_or:'or',
      landing_foot:'George Solutions · Swiss HKLS service & AI professional finder',
      // Home
      cat_handwerk:'Trades', cat_handwerk_sub:'Plumbing · Electrical · Garden · Cleaning · & more',
      cat_beauty:'Beauty', cat_beauty_sub:'Hairdresser · Nails · Massage · Barber · & more',
      nav_home:'Home', nav_scan:'Scan', nav_about:'About BOB',
      // Scan
      scan_title:'Scan problem', scan_voice:'Record voice memo',
      scan_ph:"Or type your problem... e.g. 'tap is dripping' or 'haircut'",
      ask_btn:'Ask BOB',
      // Result
      res_title:"BOB's diagnosis", res_lbl:'Diagnosis complete',
      meta_kat:'Category', meta_dring:'Urgency', meta_kost:'Cost approx.', meta_zeit:'Timeframe',
      tips_title:"BOB's tips", act_title:'What would you like to do next?',
      act_find_a:'Find a tradesperson', act_find_a_sub:'BOB finds the right professional for you',
      act_find_b:'Find a provider', act_find_b_sub:'BOB finds the right provider near you',
      price_free:'Free', price_on_order:'on booking', price_once:'one-time',
      act_angebot:'Professional quote', act_angebot_sub:'Binding quote from the professional within 24h',
      act_finder:'Find providers near you', act_finder_sub:'We email you the nearest matching providers (e.g. barbershops, nail salons).',
      act_pro:"BOB's Pro advice", act_pro_sub:'Detailed expert assessment', act_pro_basic:'basic',
      new_scan:'🔄 Start a new scan', chat_title:'💬 More questions? Ask BOB!', chat_ph:'Ask BOB something…',
      fb_q:'Was this answer helpful?', fb_yes:'Yes', fb_no:'No', fb_correct:'Correct',
      maps_title:'Professional near you', maps_sub:'Google Maps integration coming soon',
      richt_prefix:'💡 In your region', richt_mid:'this usually costs', richt_var:'varies by provider',
      // GS flow (tariff + team)
      gs_tarif_pilot_name:'Pilot', gs_tarif_pilot_desc:'Get started · 14 days / 3 weeks · then monthly contract',
      gs_tarif_monat_name:'Monthly contract', gs_tarif_monat_desc:'Ongoing support · fair fixed rates',
      gs_tarif_hint:'Hourly rate incl. expenses. Choose single or 2-person team in the next step.',
      gs_team_recommended:'Recommended', gs_team_team_tit:'👥 2-person team', gs_team_team_sub:'Two well-rehearsed pros on site',
      gs_team_single_tit:'👤 Single technician', gs_team_single_sub:'One pro on site',
      gs_tech_loading:'Loading technicians…', gs_tech_skip:'Optional – pick a preferred technician or leave it to the team.',
      gs_ki_badge:'⭐ AI recommendation', gs_ki_empfiehlt:'AI recommends',
      // GS-Flow (Kunden-Funnel) – i18n
      gsf_home_tit:'HVAC-<span>Expertise</span><br>on demand',
      gsf_home_sub:'Professional building-services solutions for companies, property managers and facility managers.',
      gsf_svc_heizung:'🔥 Heating',
      gsf_svc_sanitaer:'🚿 Plumbing',
      gsf_svc_lueftung:'💨 Ventilation',
      gsf_svc_klima:'❄️ Air conditioning',
      gsf_home_akt_t:'Offer: First 2 hours free',
      gsf_home_akt_s:'Applies from monthly contract (not the Pilot) · serious & non-binding',
      gsf_home_cta:'Start a new project',
      gsf_24h_t:'24h response promise',
      gsf_home_prom_s:'No login · Mobile first · No risk',
      gsf_home_pilotnow:'Pilot offer, now only',
      gsf_home_login:'🔑 Partner / technician login',
      gsf_phone_t:'Prefer to talk?',
      gsf_phone_s:'Intro call: info@george-solutions.ch',
      gsf_phone_num:'✉️ Write',
      gsf_nav_erfassung:'Project intake',
      gsf_nav_datenblatt:'Project data sheet',
      gsf_nav_tarif:'Choose tariff',
      gsf_nav_team:'Our team',
      gsf_nav_kontakt:'Contact & availability',
      gsf_nav_bestaet:'Confirm request',
      gsf_erf_akt_t:'First 2 hours free',
      gsf_erf_akt_s:'from monthly contract (not the Pilot)',
      gsf_l_projname:'Project name',
      gsf_ph_projname:'e.g. heating overhaul, Zurich site',
      gsf_l_bereich:'Field',
      gsf_chip_kombiniert:'🔧 Combined',
      gsf_l_objekt:'Property type',
      gsf_chip_efh:'🏠 House',
      gsf_chip_mfh:'🏢 Apartments',
      gsf_chip_gewerbe:'🏪 Commercial',
      gsf_chip_industrie:'🏭 Industrial',
      gsf_l_desc:'Project description',
      gsf_ph_desc:'Describe the project: what needs doing? what issues exist? size of the property...',
      gsf_l_dring:'Urgency',
      gsf_chip_normal:'📅 Normal',
      gsf_chip_dringend:'⚡ Urgent',
      gsf_chip_sehrdringend:'🚨 Very urgent',
      gsf_btn_analyse:'Start AI analysis',
      gsf_db_lbl:'AI analysis complete',
      gsf_db_m_umfang:'Scope',
      gsf_db_m_std:'Estimated hours',
      gsf_db_m_prio:'Priority',
      gsf_db_steps:'📋 Next steps',
      gsf_db_tech:'⚙️ Technical notes',
      gsf_btn_tarifwahl:'Choose tariff →',
      gsf_weiter:'Continue →',
      gsf_near_ph:'Your ZIP – technicians near you',
      gsf_tech_hint:'👷 Available technicians for your project',
      gsf_l_vorname:'First name *',
      gsf_l_nachname:'Last name *',
      gsf_l_firma:'Company',
      gsf_l_strasse:'Street & number *',
      gsf_l_plz:'ZIP *',
      gsf_l_ort:'City *',
      gsf_l_tel:'Phone *',
      gsf_l_email:'Email *',
      gsf_l_start:'Preferred start',
      gsf_l_infos:'Additional info',
      gsf_ph_firma:'Company name (optional)',
      gsf_ph_strasse:'e.g. Sample Street 12',
      gsf_ph_tel:'Phone / WhatsApp',
      gsf_ph_email:'Email address',
      gsf_ph_notiz:'Special notes, access info, further wishes...',
      gsf_chip_asap:'⚡ ASAP',
      gsf_chip_thisweek:'📅 This week',
      gsf_chip_nextweek:'🗓️ Next week',
      gsf_chip_open:'🔄 Flexible',
      gsf_leadhint:'📌 Please provide phone <strong>and</strong> email. If the phone number has a typo, we\'ll also reach you by email to arrange an appointment.',
      gsf_bestaet_intro:'Please review your request before sending:',
      gsf_24h_s2:'The GS team will get back to you within 24 hours.',
      gsf_btn_send:'Send request now',
      gsf_bestaet_privacy:'Your data is kept confidential and used only for this request.',
      gsf_buch_tit:'Request sent!',
      gsf_buch_sub:'The George Solutions team has received your request and will respond within 24 hours with a concrete offer.',
      gsf_tk_projekt:'Project',
      gsf_tk_tarif:'Chosen tariff',
      gsf_tk_team:'Team',
      gsf_tk_status:'Status',
      gsf_buch_status_val:'✅ Request received',
      gsf_buch_erst_t:'📞 Prefer a quick personal chat?',
      gsf_buch_erst_s:'Free intro call – we\'ll call you back within 2 hours (on business days).',
      gsf_buch_erst_btn:'📞 Request a free intro call',
      gsf_buch_erst_note:'Non-binding & free.',
      gsf_buch_acct_t:'📩 Track status live?',
      gsf_buch_acct_s:'Optional – get a login link by email to view your request & invoices.',
      gsf_buch_acct_btn:'🔑 Send login link',
      gsf_btn_neu:'+ New project',
      gsf_btn_backbob:'Back to Baby BOB',
      gsf_dyn_team_lbl:'2-person team',
      gsf_dyn_single_lbl:'Single technician',
      gsf_dyn_pp:'/h per person',
      gsf_dyn_total:'total',
      gsf_dyn_perhour:'per hour',
      gsf_dyn_perhour_total:'per hour total',
      gsf_dyn_oneonsite:'one pro on site',
      gsf_dyn_choose_team:'Choose your 2-person team',
      gsf_dyn_team_note:'Fixed, well-rehearsed 2-person teams – both pros arrive fully ready to work.',
      gsf_dyn_single_note:'Pick your preferred technician from our team – or leave the assignment to dispatch.',
      gsf_dyn_team_decides:'Team decides',
      gsf_dyn_avail_now:'available now',
      gsf_dyn_in_network:'technicians in the network',
      gsf_dyn_near:'📍 Near you',
      gsf_dyn_more_network:'More in the network',
      gsf_dyn_no_profiles:'No technician profiles are listed right now. The team will be assigned to fit your project.',
      gsf_dyn_last_upd:'Last updated',
      gsf_sum_projekt:'Project',
      gsf_sum_objekt:'Property type',
      gsf_sum_dring:'Urgency',
      gsf_sum_std:'Estimated hours',
      gsf_sum_tarif:'Chosen tariff',
      gsf_sum_team:'Team',
      gsf_sum_tech:'Technician',
      gsf_sum_wunsch:'Preferred technician',
      gsf_sum_start:'Preferred start',
      gsf_sum_vorname:'First name',
      gsf_sum_nachname:'Last name',
      gsf_sum_firma:'Company',
      gsf_sum_adresse:'Address',
      gsf_sum_tel:'Phone',
      gsf_sum_email:'Email',
    },
    fr: {
      hero_title: 'Ton chercheur', hero_sub2: 'tout-en-un',
      hero_p: 'Prends une photo ou décris ton problème – BOB te trouve le bon professionnel près de chez toi au meilleur rapport qualité-prix.',
      scan_btn: 'Scanner le problème', mic_btn: 'Parler à BOB', premium_btn: 'BOB Premium & Rapports',
      sound_on: '🔊 Activer le son', greeting: "Salut, je m'appelle Bob ! Je t'aide pour tout problème – artisanat ou beauté. Comment puis-je t'aider ?",
      intro: 'Bonjour. Je suis BOB, votre assistant technique numérique.',
      premium_title: 'BOB Premium', reports_grp: 'Rapports détaillés (paiement unique)', abos_grp: 'Abonnements',
      free: 'Free', pro: 'Pro', mute: 'Couper la lecture', unmute: 'Activer la lecture',
      region_label: 'Choisir la région', pay_secure: 'Paiement sécurisé via Stripe · Mode test',
      disclaimer: "Version de démonstration pour tests. Choisis ton pays 🇨🇭🇦🇹🇩🇪🇪🇸🇬🇧 en haut – la langue, la monnaie et la région s'adaptent. L'app finale arrive l'année prochaine.",
      disclaimer_ok: 'Compris',
      gs_badge:'Équipe pro HKLS', gs_title:'Équipe pro à la demande',
      gs_sub:'Chauffage, sanitaire, ventilation & climatisation – réservez une équipe pro HKLS entièrement équipée, à tarifs équitables et réponse sous 24h.',
      gs_cta:'Réserver un service HKLS →',
      bob_badge:'Scanner IA', bob_title:'Scanne ton problème & trouve un pro',
      bob_sub:"Prends une photo ou décris ton problème – l'IA reconnaît aussitôt quel artisan ou prestataire te convient.",
      bob_cta:'Scanner maintenant →', landing_or:'ou',
      landing_foot:'George Solutions · Service HKLS suisse & recherche de pros par IA',
      cat_handwerk:'Artisanat', cat_handwerk_sub:'Sanitaire · Électricité · Jardin · Nettoyage · etc.',
      cat_beauty:'Beauté', cat_beauty_sub:'Coiffeur · Ongles · Massage · Barbier · etc.',
      nav_home:'Accueil', nav_scan:'Scanner', nav_about:'À propos',
      scan_title:'Scanner le problème', scan_voice:'Enregistrer un mémo vocal',
      scan_ph:"Ou écris ton problème... p. ex. 'robinet qui goutte' ou 'coupe de cheveux'",
      ask_btn:'Demander à BOB',
      res_title:'Diagnostic de BOB', res_lbl:'Diagnostic terminé',
      meta_kat:'Catégorie', meta_dring:'Urgence', meta_kost:'Coût env.', meta_zeit:'Délai',
      tips_title:'Conseils de BOB', act_title:'Que veux-tu faire ensuite ?',
      act_find_a:'Trouver un artisan', act_find_a_sub:'BOB cherche le bon professionnel pour toi',
      act_find_b:'Trouver un prestataire', act_find_b_sub:'BOB trouve le bon prestataire près de chez toi',
      price_free:'Gratuit', price_on_order:'à la commande', price_once:'paiement unique',
      act_angebot:'Devis professionnel', act_angebot_sub:'Devis ferme du professionnel sous 24h',
      act_finder:'Trouver des prestataires près de chez toi', act_finder_sub:"Nous t'envoyons par e-mail les prestataires les plus proches (p. ex. barbiers, onglerie).",
      act_pro:'Conseil Pro de BOB', act_pro_sub:'Évaluation experte détaillée', act_pro_basic:'basic',
      new_scan:'🔄 Nouveau scan', chat_title:"💬 D'autres questions ? Demande à BOB !", chat_ph:'Pose une question à BOB…',
      fb_q:"Cette réponse t'a-t-elle été utile ?", fb_yes:'Oui', fb_no:'Non', fb_correct:'Corriger',
      maps_title:'Professionnel près de chez toi', maps_sub:'Intégration Google Maps bientôt disponible',
      richt_prefix:'💡 Dans ta région', richt_mid:'cela coûte généralement', richt_var:'variable selon le prestataire',
      gs_tarif_pilot_name:'Pilote', gs_tarif_pilot_desc:'Pour démarrer · 14 jours / 3 semaines · puis contrat mensuel',
      gs_tarif_monat_name:'Contrat mensuel', gs_tarif_monat_desc:'Suivi continu · conditions fixes équitables',
      gs_tarif_hint:"Tarif horaire frais compris. Choisissez individuel ou équipe de 2 à l'étape suivante.",
      gs_team_recommended:'Recommandé', gs_team_team_tit:'👥 Équipe de 2', gs_team_team_sub:'Deux pros rodés sur place',
      gs_team_single_tit:'👤 Technicien seul', gs_team_single_sub:'Un pro sur place',
      gs_tech_loading:'Chargement des techniciens…', gs_tech_skip:"Optionnel – choisissez un technicien préféré ou laissez l'équipe décider.",
      gs_ki_badge:'⭐ Recommandation IA', gs_ki_empfiehlt:"L'IA recommande",
      // GS-Flow (Kunden-Funnel) – i18n
      gsf_home_tit:'Expertise <span>CVCS</span><br>à la demande',
      gsf_home_sub:'Prestations professionnelles en technique du bâtiment pour entreprises, régies et facility managers.',
      gsf_svc_heizung:'🔥 Chauffage',
      gsf_svc_sanitaer:'🚿 Sanitaire',
      gsf_svc_lueftung:'💨 Ventilation',
      gsf_svc_klima:'❄️ Climatisation',
      gsf_home_akt_t:'Offre : 2 premières heures gratuites',
      gsf_home_akt_s:'Valable dès le contrat mensuel (pas le Pilote) · sérieux & sans engagement',
      gsf_home_cta:'Saisir un nouveau projet',
      gsf_24h_t:'Réponse garantie sous 24h',
      gsf_home_prom_s:'Sans connexion · Mobile first · Sans risque',
      gsf_home_pilotnow:'Offre Pilote, maintenant',
      gsf_home_login:'🔑 Connexion partenaire / technicien',
      gsf_phone_t:'Plutôt en personne ?',
      gsf_phone_s:'Premier échange : info@george-solutions.ch',
      gsf_phone_num:'✉️ Écrire',
      gsf_nav_erfassung:'Saisie du projet',
      gsf_nav_datenblatt:'Fiche projet',
      gsf_nav_tarif:'Choix du tarif',
      gsf_nav_team:'Notre équipe',
      gsf_nav_kontakt:'Contact & disponibilité',
      gsf_nav_bestaet:'Confirmer la demande',
      gsf_erf_akt_t:'2 premières heures gratuites',
      gsf_erf_akt_s:'dès le contrat mensuel (pas le Pilote)',
      gsf_l_projname:'Nom du projet',
      gsf_ph_projname:'p. ex. révision chauffage, site Zurich',
      gsf_l_bereich:'Domaine',
      gsf_chip_kombiniert:'🔧 Combiné',
      gsf_l_objekt:'Type de bien',
      gsf_chip_efh:'🏠 Maison',
      gsf_chip_mfh:'🏢 Immeuble',
      gsf_chip_gewerbe:'🏪 Commerce',
      gsf_chip_industrie:'🏭 Industrie',
      gsf_l_desc:'Description du projet',
      gsf_ph_desc:'Décrivez le projet : que faut-il faire ? quels problèmes ? taille du bien...',
      gsf_l_dring:'Urgence',
      gsf_chip_normal:'📅 Normal',
      gsf_chip_dringend:'⚡ Urgent',
      gsf_chip_sehrdringend:'🚨 Très urgent',
      gsf_btn_analyse:'Lancer l\'analyse IA',
      gsf_db_lbl:'Analyse IA terminée',
      gsf_db_m_umfang:'Ampleur',
      gsf_db_m_std:'Heures estimées',
      gsf_db_m_prio:'Priorité',
      gsf_db_steps:'📋 Prochaines étapes',
      gsf_db_tech:'⚙️ Notes techniques',
      gsf_btn_tarifwahl:'Choisir le tarif →',
      gsf_weiter:'Continuer →',
      gsf_near_ph:'Votre NPA – techniciens près de chez vous',
      gsf_tech_hint:'👷 Techniciens disponibles pour votre projet',
      gsf_l_vorname:'Prénom *',
      gsf_l_nachname:'Nom *',
      gsf_l_firma:'Entreprise',
      gsf_l_strasse:'Rue & numéro *',
      gsf_l_plz:'NPA *',
      gsf_l_ort:'Localité *',
      gsf_l_tel:'Téléphone *',
      gsf_l_email:'E-mail *',
      gsf_l_start:'Début souhaité',
      gsf_l_infos:'Infos complémentaires',
      gsf_ph_firma:'Nom de l\'entreprise (optionnel)',
      gsf_ph_strasse:'p. ex. Rue Exemple 12',
      gsf_ph_tel:'Téléphone / WhatsApp',
      gsf_ph_email:'Adresse e-mail',
      gsf_ph_notiz:'Particularités, accès, autres souhaits...',
      gsf_chip_asap:'⚡ ASAP',
      gsf_chip_thisweek:'📅 Cette semaine',
      gsf_chip_nextweek:'🗓️ Semaine prochaine',
      gsf_chip_open:'🔄 Date ouverte',
      gsf_leadhint:'📌 Indiquez téléphone <strong>et</strong> e-mail. En cas d\'erreur de numéro, nous vous contacterons aussi par e-mail pour fixer un rendez-vous.',
      gsf_bestaet_intro:'Veuillez vérifier votre demande avant l\'envoi :',
      gsf_24h_s2:'L\'équipe GS vous répond sous 24 heures.',
      gsf_btn_send:'Envoyer la demande',
      gsf_bestaet_privacy:'Vos données restent confidentielles et ne servent qu\'à cette demande.',
      gsf_buch_tit:'Demande envoyée !',
      gsf_buch_sub:'L\'équipe George Solutions a reçu votre demande et reviendra vers vous sous 24 heures avec une offre concrète.',
      gsf_tk_projekt:'Projet',
      gsf_tk_tarif:'Tarif choisi',
      gsf_tk_team:'Équipe',
      gsf_tk_status:'Statut',
      gsf_buch_status_val:'✅ Demande reçue',
      gsf_buch_erst_t:'📞 Plutôt un échange rapide ?',
      gsf_buch_erst_s:'Premier échange gratuit – nous vous rappelons sous 2 heures (jours ouvrés).',
      gsf_buch_erst_btn:'📞 Demander un premier échange gratuit',
      gsf_buch_erst_note:'Sans engagement & gratuit.',
      gsf_buch_acct_t:'📩 Suivre le statut en direct ?',
      gsf_buch_acct_s:'Optionnel – recevez un lien de connexion par e-mail pour voir votre demande & vos factures.',
      gsf_buch_acct_btn:'🔑 Envoyer le lien de connexion',
      gsf_btn_neu:'+ Nouveau projet',
      gsf_btn_backbob:'Retour à Baby BOB',
      gsf_dyn_team_lbl:'Équipe de 2',
      gsf_dyn_single_lbl:'Technicien seul',
      gsf_dyn_pp:'/h par personne',
      gsf_dyn_total:'au total',
      gsf_dyn_perhour:'par heure',
      gsf_dyn_perhour_total:'par heure au total',
      gsf_dyn_oneonsite:'un pro sur place',
      gsf_dyn_choose_team:'Choisissez votre équipe de 2',
      gsf_dyn_team_note:'Équipes de 2 fixes et rodées – les deux pros arrivent prêts à intervenir.',
      gsf_dyn_single_note:'Choisissez votre technicien préféré dans notre équipe – ou laissez l\'affectation à la dispo.',
      gsf_dyn_team_decides:'L\'équipe décide',
      gsf_dyn_avail_now:'disponibles maintenant',
      gsf_dyn_in_network:'techniciens dans le réseau',
      gsf_dyn_near:'📍 Près de chez vous',
      gsf_dyn_more_network:'Autres dans le réseau',
      gsf_dyn_no_profiles:'Aucun profil de technicien pour l\'instant. L\'équipe sera affectée selon votre projet.',
      gsf_dyn_last_upd:'Dernière mise à jour',
      gsf_sum_projekt:'Projet',
      gsf_sum_objekt:'Type de bien',
      gsf_sum_dring:'Urgence',
      gsf_sum_std:'Heures estimées',
      gsf_sum_tarif:'Tarif choisi',
      gsf_sum_team:'Équipe',
      gsf_sum_tech:'Technicien',
      gsf_sum_wunsch:'Technicien souhaité',
      gsf_sum_start:'Début souhaité',
      gsf_sum_vorname:'Prénom',
      gsf_sum_nachname:'Nom',
      gsf_sum_firma:'Entreprise',
      gsf_sum_adresse:'Adresse',
      gsf_sum_tel:'Téléphone',
      gsf_sum_email:'E-mail',
    },
    it: {
      hero_title: 'Il tuo cercatore', hero_sub2: 'tuttofare',
      hero_p: 'Scatta una foto o descrivi il problema – BOB ti trova il professionista giusto vicino a te con il miglior rapporto qualità-prezzo.',
      scan_btn: 'Scansiona il problema', mic_btn: 'Parla con BOB', premium_btn: 'BOB Premium e Report',
      sound_on: "🔊 Attiva l'audio", greeting: 'Ciao, mi chiamo Bob! Ti aiuto con qualsiasi problema – artigianato o bellezza. Come posso aiutarti?',
      intro: 'Buongiorno. Sono BOB, il suo assistente tecnico digitale.',
      premium_title: 'BOB Premium', reports_grp: 'Report dettagliati (pagamento unico)', abos_grp: 'Abbonamenti',
      free: 'Free', pro: 'Pro', mute: 'Disattiva lettura', unmute: 'Attiva lettura',
      region_label: 'Scegli la regione', pay_secure: 'Pagamento sicuro con Stripe · Modalità test',
      disclaimer: "Versione demo per test. Scegli il tuo paese 🇨🇭🇦🇹🇩🇪🇪🇸🇬🇧 in alto – lingua, valuta e regione si adattano. L'app finale arriverà l'anno prossimo.",
      disclaimer_ok: 'Capito',
      gs_badge:'Team pro HKLS', gs_title:'Team pro su richiesta',
      gs_sub:'Riscaldamento, sanitari, ventilazione e climatizzazione – prenota un team pro HKLS completamente attrezzato, con tariffe eque e risposta in 24h.',
      gs_cta:'Prenota un servizio HKLS →',
      bob_badge:'Scanner IA', bob_title:'Scansiona il problema e trova un pro',
      bob_sub:"Scatta una foto o descrivi il problema – l'IA riconosce subito quale artigiano o fornitore fa per te.",
      bob_cta:'Scansiona ora →', landing_or:'oppure',
      landing_foot:'George Solutions · Servizio HKLS svizzero e ricerca di professionisti con IA',
      cat_handwerk:'Artigianato', cat_handwerk_sub:'Sanitari · Elettricità · Giardino · Pulizie · ecc.',
      cat_beauty:'Bellezza', cat_beauty_sub:'Parrucchiere · Unghie · Massaggi · Barbiere · ecc.',
      nav_home:'Home', nav_scan:'Scansiona', nav_about:'Su BOB',
      scan_title:'Scansiona il problema', scan_voice:'Registra un memo vocale',
      scan_ph:"Oppure scrivi il problema... es. 'rubinetto che gocciola' o 'taglio di capelli'",
      ask_btn:'Chiedi a BOB',
      res_title:'Diagnosi di BOB', res_lbl:'Diagnosi completata',
      meta_kat:'Categoria', meta_dring:'Urgenza', meta_kost:'Costo circa', meta_zeit:'Tempistica',
      tips_title:'Consigli di BOB', act_title:'Cosa vuoi fare adesso?',
      act_find_a:'Trova un artigiano', act_find_a_sub:'BOB cerca il professionista giusto per te',
      act_find_b:'Trova un fornitore', act_find_b_sub:'BOB trova il fornitore giusto vicino a te',
      price_free:'Gratis', price_on_order:"all'ordine", price_once:'pagamento unico',
      act_angebot:'Preventivo professionale', act_angebot_sub:'Preventivo vincolante dal professionista in 24h',
      act_finder:'Trova fornitori vicino a te', act_finder_sub:'Ti inviamo via e-mail i fornitori più vicini adatti (es. barbieri, centri estetici).',
      act_pro:'Consiglio Pro di BOB', act_pro_sub:'Valutazione esperta dettagliata', act_pro_basic:'basic',
      new_scan:'🔄 Nuova scansione', chat_title:'💬 Altre domande? Chiedi a BOB!', chat_ph:'Chiedi qualcosa a BOB…',
      fb_q:'Questa risposta ti è stata utile?', fb_yes:'Sì', fb_no:'No', fb_correct:'Correggi',
      maps_title:'Professionista vicino a te', maps_sub:'Integrazione Google Maps in arrivo',
      richt_prefix:'💡 Nella tua regione', richt_mid:'di solito costa', richt_var:'variabile secondo il fornitore',
      gs_tarif_pilot_name:'Pilota', gs_tarif_pilot_desc:'Per iniziare · 14 giorni / 3 settimane · poi contratto mensile',
      gs_tarif_monat_name:'Contratto mensile', gs_tarif_monat_desc:'Assistenza continua · condizioni fisse eque',
      gs_tarif_hint:'Tariffa oraria spese incluse. Scegli singolo o team di 2 nel passaggio successivo.',
      gs_team_recommended:'Consigliato', gs_team_team_tit:'👥 Team di 2', gs_team_team_sub:'Due professionisti affiatati sul posto',
      gs_team_single_tit:'👤 Tecnico singolo', gs_team_single_sub:'Un professionista sul posto',
      gs_tech_loading:'Caricamento tecnici…', gs_tech_skip:'Opzionale – scegli un tecnico preferito o lascia decidere al team.',
      gs_ki_badge:'⭐ Raccomandazione IA', gs_ki_empfiehlt:"L'IA consiglia",
      // GS-Flow (Kunden-Funnel) – i18n
      gsf_home_tit:'Competenza <span>HKLS</span><br>su richiesta',
      gsf_home_sub:'Servizi professionali di tecnica degli edifici per aziende, amministrazioni immobiliari e facility manager.',
      gsf_svc_heizung:'🔥 Riscaldamento',
      gsf_svc_sanitaer:'🚿 Sanitari',
      gsf_svc_lueftung:'💨 Ventilazione',
      gsf_svc_klima:'❄️ Climatizzazione',
      gsf_home_akt_t:'Promo: prime 2 ore gratis',
      gsf_home_akt_s:'Valido dal contratto mensile (non con il Pilota) · serio e senza impegno',
      gsf_home_cta:'Avvia un nuovo progetto',
      gsf_24h_t:'Risposta garantita in 24h',
      gsf_home_prom_s:'Nessun login · Mobile first · Nessun rischio',
      gsf_home_pilotnow:'Promo Pilota, solo ora',
      gsf_home_login:'🔑 Login partner / tecnico',
      gsf_phone_t:'Preferisci parlarne?',
      gsf_phone_s:'Primo colloquio: info@george-solutions.ch',
      gsf_phone_num:'✉️ Scrivi',
      gsf_nav_erfassung:'Inserimento progetto',
      gsf_nav_datenblatt:'Scheda progetto',
      gsf_nav_tarif:'Scelta tariffa',
      gsf_nav_team:'Il nostro team',
      gsf_nav_kontakt:'Contatto e disponibilità',
      gsf_nav_bestaet:'Conferma richiesta',
      gsf_erf_akt_t:'Prime 2 ore gratis',
      gsf_erf_akt_s:'dal contratto mensile (non con il Pilota)',
      gsf_l_projname:'Nome progetto',
      gsf_ph_projname:'es. revisione riscaldamento, sede Zurigo',
      gsf_l_bereich:'Settore',
      gsf_chip_kombiniert:'🔧 Combinato',
      gsf_l_objekt:'Tipo di immobile',
      gsf_chip_efh:'🏠 Casa',
      gsf_chip_mfh:'🏢 Condominio',
      gsf_chip_gewerbe:'🏪 Commerciale',
      gsf_chip_industrie:'🏭 Industria',
      gsf_l_desc:'Descrizione del progetto',
      gsf_ph_desc:'Descriva il progetto: cosa va fatto? quali problemi? dimensione dell\'immobile...',
      gsf_l_dring:'Urgenza',
      gsf_chip_normal:'📅 Normale',
      gsf_chip_dringend:'⚡ Urgente',
      gsf_chip_sehrdringend:'🚨 Molto urgente',
      gsf_btn_analyse:'Avvia analisi IA',
      gsf_db_lbl:'Analisi IA completata',
      gsf_db_m_umfang:'Entità',
      gsf_db_m_std:'Ore stimate',
      gsf_db_m_prio:'Priorità',
      gsf_db_steps:'📋 Prossimi passi',
      gsf_db_tech:'⚙️ Note tecniche',
      gsf_btn_tarifwahl:'Scegli tariffa →',
      gsf_weiter:'Continua →',
      gsf_near_ph:'Il tuo CAP – tecnici vicino a te',
      gsf_tech_hint:'👷 Tecnici disponibili per il tuo progetto',
      gsf_l_vorname:'Nome *',
      gsf_l_nachname:'Cognome *',
      gsf_l_firma:'Azienda',
      gsf_l_strasse:'Via e numero *',
      gsf_l_plz:'CAP *',
      gsf_l_ort:'Località *',
      gsf_l_tel:'Telefono *',
      gsf_l_email:'E-mail *',
      gsf_l_start:'Inizio desiderato',
      gsf_l_infos:'Informazioni aggiuntive',
      gsf_ph_firma:'Nome azienda (opzionale)',
      gsf_ph_strasse:'es. Via Esempio 12',
      gsf_ph_tel:'Telefono / WhatsApp',
      gsf_ph_email:'Indirizzo e-mail',
      gsf_ph_notiz:'Particolarità, accessi, altre richieste...',
      gsf_chip_asap:'⚡ ASAP',
      gsf_chip_thisweek:'📅 Questa settimana',
      gsf_chip_nextweek:'🗓️ Prossima settimana',
      gsf_chip_open:'🔄 Data aperta',
      gsf_leadhint:'📌 Indichi telefono <strong>ed</strong> e-mail. In caso di errore nel numero, la contatteremo anche via e-mail per fissare un appuntamento.',
      gsf_bestaet_intro:'Controlli la sua richiesta prima di inviare:',
      gsf_24h_s2:'Il team GS la ricontatta entro 24 ore.',
      gsf_btn_send:'Invia la richiesta',
      gsf_bestaet_privacy:'I suoi dati restano riservati e usati solo per questa richiesta.',
      gsf_buch_tit:'Richiesta inviata!',
      gsf_buch_sub:'Il team George Solutions ha ricevuto la sua richiesta e risponderà entro 24 ore con un\'offerta concreta.',
      gsf_tk_projekt:'Progetto',
      gsf_tk_tarif:'Tariffa scelta',
      gsf_tk_team:'Team',
      gsf_tk_status:'Stato',
      gsf_buch_status_val:'✅ Richiesta ricevuta',
      gsf_buch_erst_t:'📞 Preferisci un contatto rapido?',
      gsf_buch_erst_s:'Primo colloquio gratuito – la richiamiamo entro 2 ore (nei giorni feriali).',
      gsf_buch_erst_btn:'📞 Richiedi un primo colloquio gratuito',
      gsf_buch_erst_note:'Senza impegno e gratuito.',
      gsf_buch_acct_t:'📩 Seguire lo stato in tempo reale?',
      gsf_buch_acct_s:'Opzionale – ricevi un link di accesso via e-mail per vedere richiesta e fatture.',
      gsf_buch_acct_btn:'🔑 Invia link di accesso',
      gsf_btn_neu:'+ Nuovo progetto',
      gsf_btn_backbob:'Torna a Baby BOB',
      gsf_dyn_team_lbl:'Team di 2',
      gsf_dyn_single_lbl:'Tecnico singolo',
      gsf_dyn_pp:'/h a persona',
      gsf_dyn_total:'totale',
      gsf_dyn_perhour:'all\'ora',
      gsf_dyn_perhour_total:'all\'ora in totale',
      gsf_dyn_oneonsite:'un professionista sul posto',
      gsf_dyn_choose_team:'Scegli il tuo team di 2',
      gsf_dyn_team_note:'Team di 2 fissi e affiatati – entrambi i professionisti arrivano pronti all\'opera.',
      gsf_dyn_single_note:'Scegli il tuo tecnico preferito dal nostro team – o lascia l\'assegnazione alla centrale.',
      gsf_dyn_team_decides:'Decide il team',
      gsf_dyn_avail_now:'disponibili ora',
      gsf_dyn_in_network:'tecnici nella rete',
      gsf_dyn_near:'📍 Vicino a te',
      gsf_dyn_more_network:'Altri nella rete',
      gsf_dyn_no_profiles:'Al momento nessun profilo tecnico. Il team sarà assegnato in base al progetto.',
      gsf_dyn_last_upd:'Ultimo aggiornamento',
      gsf_sum_projekt:'Progetto',
      gsf_sum_objekt:'Tipo di immobile',
      gsf_sum_dring:'Urgenza',
      gsf_sum_std:'Ore stimate',
      gsf_sum_tarif:'Tariffa scelta',
      gsf_sum_team:'Team',
      gsf_sum_tech:'Tecnico',
      gsf_sum_wunsch:'Tecnico preferito',
      gsf_sum_start:'Inizio desiderato',
      gsf_sum_vorname:'Nome',
      gsf_sum_nachname:'Cognome',
      gsf_sum_firma:'Azienda',
      gsf_sum_adresse:'Indirizzo',
      gsf_sum_tel:'Telefono',
      gsf_sum_email:'E-mail',
    },
  };
  function t(key, lang) { var L = STR[lang] || STR.de; return (key in L) ? L[key] : (STR.de[key] || key); }

  window.BB_REGIONS = REGIONS;
  window.BB_REGION_ORDER = ORDER;
  window.bbFormatPrice = formatPrice;
  window.bbDetectRegion = detectRegion;
  window.bbT = t;
})();
